# Generated by Django 5.0.4 on 2024-05-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_categoria_rename_image_produto_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='imagem',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
